stages:
    - deploy
    - migrate

heroku:
    image: wingrunr21/alpine-heroku-cli:7.4.11
    stage: deploy
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/tcrpartybot.git
        - git push -f heroku master

migration:
    image: migrate/migrate
    stage: migrate
    script:
        - migrate -source file://./migrations -database "$DATABASE" up
